dist: focal
group: travis_latest
version: ~> 1.0

os: linux
language: c

before_install:
  - sudo apt-get -y install libpcre2-dev

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - ./bootstrap.sh
  - ./configure && make
